server:
  port: 8081

spring:
  application:
    name: washington-wash-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://103.40.13.47:7322/WASHINGTON_WASH?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: public_root
    password: NIGANJIECHIWODESHUJUKU,WOJIUCAOSINIDEMA!
    driver-class-name: com.mysql.cj.jdbc.Driver

dubbo:
  application:
    name: washington-order
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848
